name: Codety
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  Codety_pipe2:
    runs-on: ubuntu-latest
    container:
      image: codetyio/codety:0.002
    steps:
#      - uses: actions/checkout@main
      - run: ls -ls

